// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxmitvkinmrcviecftmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bWl0dmtpbm1yY3ZpZWNmdG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDMyNTQsImV4cCI6MjA3MDIxOTI1NH0.SabyGCV4i3Gkce5nqRaMgBAIghCnVISf1hxZzpaT-vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});